// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVUfFYsvB7MXJWxkyAAy7_Q4iEnBgPhYQ',
    appId: '1:892100276422:web:5f95d6d651e2a66680e7c7',
    messagingSenderId: '892100276422',
    projectId: 'hayden-firebase-bloc-sign-in',
    authDomain: 'hayden-firebase-bloc-sign-in.firebaseapp.com',
    storageBucket: 'hayden-firebase-bloc-sign-in.appspot.com',
    measurementId: 'G-YPFWF4Y2H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5BsH0vekEa7yrT39PybRIg5m0tYMxGvk',
    appId: '1:892100276422:android:026f8887df8b5a2f80e7c7',
    messagingSenderId: '892100276422',
    projectId: 'hayden-firebase-bloc-sign-in',
    storageBucket: 'hayden-firebase-bloc-sign-in.appspot.com',
  );
}
